### ISSUE TITLE
SignInHubActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner'

### ISSUE THREAD

**Issue by neckaros** [aarajput/wc_flutter_share#9]
hello,

it might be an issue on firebase_auth part but it only happens if i add your library. as soon as i add your package i get the following error when i try to login and it completely crash the app (add to find the logs in logcat)
` java.lang.IncompatibleClassChangeError: Class 'com.google.android.gms.auth.api.signin.internal.SignInHubActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'androidx.lifecycle.LiveData' appears in /data/app/org.jezequel.redseat-FYIyC0un5PLI_-vjyYNrvA==/base.apk)
        at androidx.lifecycle.LiveData.observe(LiveData.java:172)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
        at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
        at androidx.loader.app.LoaderManagerImpl.initLoader(LoaderManagerImpl.java:421)
        at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.zzn(Unknown Source:80)
        at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.onActivityResult(Unknown Source:68)
        at android.app.Activity.dispatchActivityResult(Activity.java:7758)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4582)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4631)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
2020-01-06 23:45:23.408 18484-18484/? I/Process: Sending signal. PID: 18484 SIG: 9
`

any idea what might be causing this?
My project was already on androidX (still tried to do the migration in android studio but still only crash once i add your package)

**Comment by neckaros** [comment]
I solved this issue by adding:
`    def appcompat_version = "1.1.0"
    implementation "androidx.appcompat:appcompat:$appcompat_version"`

to my app module gradle dependencies
